# version: 0.0
# os: linux
# files:
#     - source: /
#       destination: /apps/deloytest
# hooks:
# #  ApplicationStop:
# #    - location: deployment.js
# #      timeout: 180
#   BeforeInstall:
#     - location: deployment.js
#       timeout: 180
#   AfterInstall:
#     - location: deployment.js
#       timeout: 180
#   ApplicationStart:
#     - location: deployment.js
#       timeout: 180
#   ValidateService:
#     - location: deployment.js
#       timeout: 180

version: 0.0
os: linux
files:
    - source: /
      destination: /var/api/
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60